### ISSUE TITLE
Treat `Overall Grade` the same as any other category

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook#42]
Currently, the calculation of the Overall Grade is handled separately from other categories and computed after the main calculations in `get_grades()` are complete. Update to an alternative structure where Overall Grade can be put at the top of the tree and act like any other category. See examples below.

```yaml
# Current
categories:
  - category: Homework
    aggregation: equally_weighted
    assignments:
      - "Homework 1"
      - "Homework 2"
  - category: Midterm
    aggregation: none
    assignments:
      - "Midterm Exam"
  - category: Final
    aggregation: none
    assignments:
      - "Final Exam"
  - category: Overall Grade
    aggregation: weighted_mean
    weights: 
    - 0.20
    - 0.40
    - 0.40
    assignments:
      - "Homework"
      - "Midterm"
      - "Final"

# Alt
categories:
  category: Overall Grade
  aggregation: weighted_mean
  assignments:
    - category: Homework
      weight: 0.20
      aggregation: equally_weighted
      assignments:
        - "Homework 1"
        - "Homework 2"
    - category: Midterm
      weight: 0.40
      aggregation: none
      assignments:
        - "Midterm Exam"
    - category: Final
      weight: 0.40
      aggregation: none
      assignments:
        - "Final Exam"
```
This change will involve:

- [x] Allow weights to be stored at the category/assignment level
- [x] Be sure you can re-use assignment names in a policy file (if the Overall Grade is the max of two different grading policies, (say one with a project, one without), you'll need to be able to add the project twice).
- [x] Line 253 of `weighted_mean()`: remove the if statement to guard against dimension mismatch. Let it error out and add warning message to validate. @nikita-jaya @mvoutov 
- [x] Rename key from weights to `weight`.

See the [companion issue](https://github.com/gradebook-dev/gradebook-app/issues/94) in the app repo.
