### ISSUE TITLE
Grade aggregation silently ignoring assignments

### ISSUE THREAD

**Issue by rgiordan** [gradebook-dev/gradebook#90]
In the attached policy and grades csv, the FinalProject grade is not being computed correctly.  The "First Draft" and "First Draft Feedback" columns are being silently ignored.  You can see in the R script that the needed columns are present in gs_data but absent in the grades, and that only the "Final Draft" column is being used to compute the grades.  Other columns that seem to be similarly formatted are being read correctly, and I haven't been able to figure out what's going on.

It's a little worrying that this happened silently, and I am just lucky to have noticed it by doing a lot of manual checks.

I can't attach yml or R so I'll put the code down below.

[grades_combined_anon.csv](https://github.com/user-attachments/files/18256904/grades_combined_anon.csv)

YML file:
```
coursewide:
  course_name: STAT151A_Fall_2024
  description: Description
categories:
- category: Overall Grade
  weight: 1.0
  aggregation: weighted_mean
  assignments:
  - category: Quizzes
    weight: 0.3
    drop_n_lowest: 1
    aggregation: equally_weighted
    assignments:
    - Quiz 1
    - Quiz 2
    - Quiz 3
    - Quiz 4
    - Quiz 5
  - category: FinalExam
    weight: 0.15
    aggregation: equally_weighted
    assignments: Final Exam
  - category: FinalProject
    weight: 0.15
    aggregation: weighted_mean
    assignments:
    - category: First Draft
      weight: 0.1
      aggregation: equally_weighted
      assignments: 'Final project first draft: feedback received (8835388)'
    - category: First Draft Feedback
      weight: 0.1
      aggregation: equally_weighted
      assignments: 'Final project first draft: feedback given (8835389)'
    - category: Final Draft
      weight: 0.8
      aggregation: equally_weighted
      assignments: Final project final draft
  - category: Attendance
    weight: 0.1
    drop_n_lowest: 5
    aggregation: equally_weighted
    assignments:
    - Attendance 9/17 (actually graded)
    - Attendance 9/24
    - Attendance 9/26
    - Attendance 9/19
    - Attendance 10/8
    - Attendance 10/1
    - Attendance 10/10
    - Attendance 10/15
    - Attendance 10/17
    - Attendance 10/22
    - Attendance 10/24
    - Attendance 10/29
    - Attendance 10/3
    - Attendance 10/31
    - Attendance 11/12
    - Attendance 11/14
    - Attendance 11/7
    - Attendance 11/21
    - Course Evaluation
  - category: Homework
    weight: 0.3
    drop_n_lowest: 2
    aggregation: equally_weighted
    assignments:
    - category: HW1
      aggregation: weighted_mean
      assignments:
      - category: HW1 accuracy
        weight: 0.2
        aggregation: equally_weighted
        assignments: Homework 1
      - category: HW1 completeness
        weight: 0.8
        aggregation: equally_weighted
        assignments: HW1 completeness (8822436)
    - category: HW2
      aggregation: weighted_mean
      assignments:
      - category: HW2 accuracy
        weight: 0.2
        aggregation: equally_weighted
        assignments: Homework 2
      - category: HW2 completeness
        weight: 0.8
        aggregation: equally_weighted
        assignments: HW2 completeness (8822437)
    - category: HW3
      aggregation: weighted_mean
      assignments:
      - category: HW3 accuracy
        weight: 0.2
        aggregation: equally_weighted
        assignments: Homework 3
      - category: HW3 completeness
        weight: 0.8
        aggregation: equally_weighted
        assignments: HW3 completeness (8822438)
    - category: HW4
      aggregation: weighted_mean
      assignments:
      - category: HW4 accuracy
        weight: 0.2
        aggregation: equally_weighted
        assignments: Homework 4
      - category: HW4 completeness
        weight: 0.8
        aggregation: equally_weighted
        assignments: HW4 completeness (8822439)
    - category: HW5
      aggregation: weighted_mean
      assignments:
      - category: HW5 accuracy
        weight: 0.2
        aggregation: equally_weighted
        assignments: Homework 5
      - category: HW5 completeness
        weight: 0.8
        aggregation: equally_weighted
        assignments: HW5 completeness (8822440)
exceptions: []
```

R script:
```
# https://github.com/gradebook-dev/gradebook
library(tidyverse)
library(gradebook)

GetCols <- function(pattern, s) {
  s[grepl(pattern, s)]
}

gs_data <- read_gs("grades_combined_anon.csv")
policy <- read_policy("policy.yml")
grades <- get_grades(policy=policy, gs=gs_data, verbose=TRUE)


if (FALSE) {
  gs_data["Final project first draft: feedback received (8835388)"]
  draft_cols <-  GetCols("Final project first draft:.*", names(gs_data))
  # View(gs_data[draft_cols])
  gs_data["Final project final draft"]
  gs_data[  GetCols("HW1 completeness.*", names(gs_data))]
  any(is.na(gs_data["HW1 completeness (8822436)"]))
  gs_data[c(
    "HW1 completeness (8822436)",
    "Final project first draft: feedback received (8835388)",
    "Final project first draft: feedback given (8835389)",
    "Final project final draft"
  )] %>% View()
}

if (FALSE) {
  # The FinalProject is being computed only from the Final Draft
  grades["FinalProject"]
  grades["Final Draft"]
  grades["FinalProject"] - grades["Final Draft"]

  # All the first draft columns are missing from grades, though they
  # are present in gs_data
  gs_data["Final project first draft: feedback given (8835389)"]
  gs_data["Final project first draft: feedback given (8835389) - Max Points"]  

  grades["Final project first draft: feedback given (8835389)"]  
  grades["First Draft Feedback"]
  grades["First Draft"]
  
  GetCols("FinalProject.*", names(grades))
  GetCols("First Draft.*", names(grades))
  GetCols("Final project first draft:.*", names(grades))
  GetCols("Final project.*", names(grades))
  
  # These (similar columns) show up
  GetCols("HW1.*", names(grades))
}
```
